"""initial_migration

Revision ID: 3e798dd4bfb9
Revises:
Create Date: 2026-07-22 14:41:29.478920+09:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3e798dd4bfb9"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "markets",
        sa.Column(
            "market_code",
            sa.String(length=10),
            nullable=False,
            comment="市場コード（J-Quants API）",
        ),
        sa.Column("market_name", sa.String(length=100), nullable=False, comment="市場名"),
        sa.Column("market_short_name", sa.String(length=50), nullable=False, comment="短縮名"),
        sa.Column(
            "market_abbreviation",
            sa.String(length=10),
            nullable=False,
            comment="略号（PR/ST/GR等）",
        ),
        sa.Column(
            "market_category",
            sa.String(length=50),
            nullable=False,
            comment="カテゴリ（PRIME/STANDARD/GROWTH）",
        ),
        sa.Column(
            "market_type",
            sa.String(length=50),
            nullable=True,
            comment="市場種別（内国株式/外国株式）",
        ),
        sa.Column("sort_order", sa.Integer(), nullable=False, comment="表示順"),
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="主キー（UUID）",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="作成日時",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="更新日時",
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="市場マスタ（プライム/スタンダード/グロース等）",
    )
    op.create_index(
        op.f("ix_markets_market_category"), "markets", ["market_category"], unique=False
    )
    op.create_index(op.f("ix_markets_market_code"), "markets", ["market_code"], unique=True)
    op.create_table(
        "rounds",
        sa.Column(
            "round_id", sa.String(length=20), nullable=False, comment="ラウンドID（ビジネスキー）"
        ),
        sa.Column("round_type", sa.String(length=10), nullable=False, comment="BUY / SELL"),
        sa.Column("start_date", sa.Date(), nullable=False, comment="開始日（月曜）"),
        sa.Column("end_date", sa.Date(), nullable=False, comment="終了日（金曜）"),
        sa.Column("status", sa.String(length=20), nullable=False, comment="ACTIVE / CLOSED"),
        sa.Column(
            "model_version", sa.String(length=20), nullable=True, comment="使用したモデルバージョン"
        ),
        sa.Column(
            "feature_version",
            sa.String(length=10),
            nullable=True,
            comment="使用した特徴量バージョン",
        ),
        sa.Column("prediction_date", sa.Date(), nullable=True, comment="予測実施日"),
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="主キー（UUID）",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="作成日時",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="更新日時",
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="ラウンド管理",
    )
    op.create_index(op.f("ix_rounds_round_id"), "rounds", ["round_id"], unique=True)
    op.create_index(op.f("ix_rounds_status"), "rounds", ["status"], unique=False)
    op.create_table(
        "sectors",
        sa.Column(
            "sector_code", sa.String(length=10), nullable=False, comment="業種コード（33業種分類）"
        ),
        sa.Column("sector_name", sa.String(length=100), nullable=False, comment="業種名"),
        sa.Column("sector_name_en", sa.String(length=100), nullable=True, comment="業種名（英語）"),
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="主キー（UUID）",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="作成日時",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="更新日時",
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="業種マスタ（33業種分類）",
    )
    op.create_index(op.f("ix_sectors_sector_code"), "sectors", ["sector_code"], unique=True)
    op.create_table(
        "round_recommendations",
        sa.Column("round_id", sa.Uuid(), nullable=False, comment="ラウンドID（UUID）"),
        sa.Column("stock_code", sa.String(length=10), nullable=False, comment="銘柄コード"),
        sa.Column("rank", sa.Integer(), nullable=False, comment="推奨順位（1〜N位）"),
        sa.Column(
            "predicted_return",
            sa.Numeric(precision=8, scale=4),
            nullable=True,
            comment="予測騰落率",
        ),
        sa.Column(
            "confidence_score",
            sa.Numeric(precision=5, scale=4),
            nullable=True,
            comment="信頼度スコア（0〜1）",
        ),
        sa.Column(
            "reason_features",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="推奨理由となった特徴量",
        ),
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="主キー（UUID）",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="作成日時",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="更新日時",
        ),
        sa.ForeignKeyConstraint(
            ["round_id"],
            ["rounds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="ラウンド推奨銘柄",
    )
    op.create_index(
        op.f("ix_round_recommendations_round_id"),
        "round_recommendations",
        ["round_id"],
        unique=False,
    )
    op.create_table(
        "stock_master",
        sa.Column(
            "stock_code", sa.String(length=10), nullable=False, comment="銘柄コード（ビジネスキー）"
        ),
        sa.Column("company_name", sa.String(length=255), nullable=False, comment="会社名"),
        sa.Column("company_name_en", sa.String(length=255), nullable=True, comment="英語名"),
        sa.Column(
            "sector_code", sa.String(length=10), nullable=True, comment="業種コード（33業種分類）"
        ),
        sa.Column("market_code", sa.String(length=10), nullable=True, comment="市場区分コード"),
        sa.Column("listing_date", sa.Date(), nullable=True, comment="上場日"),
        sa.Column("delisting_date", sa.Date(), nullable=True, comment="上場廃止日"),
        sa.Column("is_active", sa.Boolean(), nullable=False, comment="上場中フラグ"),
        sa.Column(
            "market_cap",
            sa.Numeric(precision=15, scale=2),
            nullable=True,
            comment="時価総額（最新）",
        ),
        sa.Column("fetched_at", sa.DateTime(), nullable=False, comment="API取得日時"),
        sa.Column("is_nikkei225", sa.Boolean(), nullable=False, comment="日経225組入銘柄フラグ"),
        sa.Column("is_topix", sa.Boolean(), nullable=False, comment="TOPIX組入銘柄フラグ"),
        sa.Column(
            "is_topix_core30", sa.Boolean(), nullable=False, comment="TOPIX Core30組入銘柄フラグ"
        ),
        sa.Column("is_jpx400", sa.Boolean(), nullable=False, comment="JPX日経400組入銘柄フラグ"),
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="主キー（UUID）",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="作成日時",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="更新日時",
        ),
        sa.ForeignKeyConstraint(
            ["market_code"],
            ["markets.market_code"],
        ),
        sa.ForeignKeyConstraint(
            ["sector_code"],
            ["sectors.sector_code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stock_master_is_active"), "stock_master", ["is_active"], unique=False)
    op.create_index(
        op.f("ix_stock_master_is_nikkei225"), "stock_master", ["is_nikkei225"], unique=False
    )
    op.create_index(op.f("ix_stock_master_is_topix"), "stock_master", ["is_topix"], unique=False)
    op.create_index(
        op.f("ix_stock_master_market_code"), "stock_master", ["market_code"], unique=False
    )
    op.create_index(
        op.f("ix_stock_master_sector_code"), "stock_master", ["sector_code"], unique=False
    )
    op.create_index(op.f("ix_stock_master_stock_code"), "stock_master", ["stock_code"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stock_master_stock_code"), table_name="stock_master")
    op.drop_index(op.f("ix_stock_master_sector_code"), table_name="stock_master")
    op.drop_index(op.f("ix_stock_master_market_code"), table_name="stock_master")
    op.drop_index(op.f("ix_stock_master_is_topix"), table_name="stock_master")
    op.drop_index(op.f("ix_stock_master_is_nikkei225"), table_name="stock_master")
    op.drop_index(op.f("ix_stock_master_is_active"), table_name="stock_master")
    op.drop_table("stock_master")
    op.drop_index(op.f("ix_round_recommendations_round_id"), table_name="round_recommendations")
    op.drop_table("round_recommendations")
    op.drop_index(op.f("ix_sectors_sector_code"), table_name="sectors")
    op.drop_table("sectors")
    op.drop_index(op.f("ix_rounds_status"), table_name="rounds")
    op.drop_index(op.f("ix_rounds_round_id"), table_name="rounds")
    op.drop_table("rounds")
    op.drop_index(op.f("ix_markets_market_code"), table_name="markets")
    op.drop_index(op.f("ix_markets_market_category"), table_name="markets")
    op.drop_table("markets")
    # ### end Alembic commands ###
