"""change volume columns to bigint in technical_indicators

Revision ID: d5bf6dc23677
Revises: f9g0h1i2j3k4
Create Date: 2026-07-28 21:57:57.667593+09:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d5bf6dc23677"
down_revision: str | None = "f9g0h1i2j3k4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Change volume-related columns from INTEGER to BIGINT
    op.alter_column(
        "technical_indicators",
        "volume_ma_5",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="5日平均出来高",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "volume_ma_10",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="10日平均出来高",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "volume_ma_20",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="20日平均出来高",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "volume_ma_60",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="60日平均出来高",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "obv",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="OBV",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "obv_ma_20",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_comment="20日OBV移動平均",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert volume-related columns from BIGINT to INTEGER
    op.alter_column(
        "technical_indicators",
        "obv_ma_20",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="20日OBV移動平均",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "obv",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="OBV",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "volume_ma_60",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="60日平均出来高",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "volume_ma_20",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="20日平均出来高",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "volume_ma_10",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="10日平均出来高",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "volume_ma_5",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_comment="5日平均出来高",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
