"""increase precision for percentage and ratio columns

Revision ID: 02b740f637ec
Revises: d5bf6dc23677
Create Date: 2026-07-28 22:07:06.730045+09:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "02b740f637ec"
down_revision: str | None = "d5bf6dc23677"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Increase precision for percentage and ratio columns (8,4 -> 12,4)
    op.alter_column(
        "technical_indicators",
        "return_1d",
        existing_type=sa.NUMERIC(precision=8, scale=4),
        type_=sa.Numeric(precision=12, scale=4),
        existing_comment="1日騰落率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "return_3d",
        existing_type=sa.NUMERIC(precision=8, scale=4),
        type_=sa.Numeric(precision=12, scale=4),
        existing_comment="3日騰落率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "return_5d",
        existing_type=sa.NUMERIC(precision=8, scale=4),
        type_=sa.Numeric(precision=12, scale=4),
        existing_comment="5日騰落率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "return_10d",
        existing_type=sa.NUMERIC(precision=8, scale=4),
        type_=sa.Numeric(precision=12, scale=4),
        existing_comment="10日騰落率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "return_20d",
        existing_type=sa.NUMERIC(precision=8, scale=4),
        type_=sa.Numeric(precision=12, scale=4),
        existing_comment="20日騰落率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "return_60d",
        existing_type=sa.NUMERIC(precision=8, scale=4),
        type_=sa.Numeric(precision=12, scale=4),
        existing_comment="60日騰落率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "return_120d",
        existing_type=sa.NUMERIC(precision=8, scale=4),
        type_=sa.Numeric(precision=12, scale=4),
        existing_comment="120日騰落率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "roc_12",
        existing_type=sa.NUMERIC(precision=8, scale=4),
        type_=sa.Numeric(precision=12, scale=4),
        existing_comment="12日ROC",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "roc_25",
        existing_type=sa.NUMERIC(precision=8, scale=4),
        type_=sa.Numeric(precision=12, scale=4),
        existing_comment="25日ROC",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "volume_ratio_5",
        existing_type=sa.NUMERIC(precision=8, scale=4),
        type_=sa.Numeric(precision=12, scale=4),
        existing_comment="出来高比率（5日）",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "volume_ratio_20",
        existing_type=sa.NUMERIC(precision=8, scale=4),
        type_=sa.Numeric(precision=12, scale=4),
        existing_comment="出来高比率（20日）",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "volume_change_1d",
        existing_type=sa.NUMERIC(precision=8, scale=4),
        type_=sa.Numeric(precision=12, scale=4),
        existing_comment="1日出来高変化率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "volume_change_5d",
        existing_type=sa.NUMERIC(precision=8, scale=4),
        type_=sa.Numeric(precision=12, scale=4),
        existing_comment="5日出来高変化率",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert precision for percentage and ratio columns (12,4 -> 8,4)
    op.alter_column(
        "technical_indicators",
        "volume_change_5d",
        existing_type=sa.Numeric(precision=12, scale=4),
        type_=sa.NUMERIC(precision=8, scale=4),
        existing_comment="5日出来高変化率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "volume_change_1d",
        existing_type=sa.Numeric(precision=12, scale=4),
        type_=sa.NUMERIC(precision=8, scale=4),
        existing_comment="1日出来高変化率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "volume_ratio_20",
        existing_type=sa.Numeric(precision=12, scale=4),
        type_=sa.NUMERIC(precision=8, scale=4),
        existing_comment="出来高比率（20日）",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "volume_ratio_5",
        existing_type=sa.Numeric(precision=12, scale=4),
        type_=sa.NUMERIC(precision=8, scale=4),
        existing_comment="出来高比率（5日）",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "roc_25",
        existing_type=sa.Numeric(precision=12, scale=4),
        type_=sa.NUMERIC(precision=8, scale=4),
        existing_comment="25日ROC",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "roc_12",
        existing_type=sa.Numeric(precision=12, scale=4),
        type_=sa.NUMERIC(precision=8, scale=4),
        existing_comment="12日ROC",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "return_120d",
        existing_type=sa.Numeric(precision=12, scale=4),
        type_=sa.NUMERIC(precision=8, scale=4),
        existing_comment="120日騰落率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "return_60d",
        existing_type=sa.Numeric(precision=12, scale=4),
        type_=sa.NUMERIC(precision=8, scale=4),
        existing_comment="60日騰落率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "return_20d",
        existing_type=sa.Numeric(precision=12, scale=4),
        type_=sa.NUMERIC(precision=8, scale=4),
        existing_comment="20日騰落率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "return_10d",
        existing_type=sa.Numeric(precision=12, scale=4),
        type_=sa.NUMERIC(precision=8, scale=4),
        existing_comment="10日騰落率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "return_5d",
        existing_type=sa.Numeric(precision=12, scale=4),
        type_=sa.NUMERIC(precision=8, scale=4),
        existing_comment="5日騰落率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "return_3d",
        existing_type=sa.Numeric(precision=12, scale=4),
        type_=sa.NUMERIC(precision=8, scale=4),
        existing_comment="3日騰落率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "return_1d",
        existing_type=sa.Numeric(precision=12, scale=4),
        type_=sa.NUMERIC(precision=8, scale=4),
        existing_comment="1日騰落率",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
