"""Add financial_statements table (complete)

Revision ID: fa58d7eb71d8
Revises: dc9369ff3362
Create Date: 2026-07-29 20:51:12.709595+09:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fa58d7eb71d8"
down_revision: str | None = "dc9369ff3362"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "financial_statements",
        sa.Column("stock_code", sa.String(length=10), nullable=False, comment="銘柄コード"),
        sa.Column("disc_date", sa.Date(), nullable=False, comment="開示日"),
        sa.Column("disc_time", sa.String(length=20), nullable=True, comment="開示時刻"),
        sa.Column("disc_no", sa.String(length=50), nullable=True, comment="開示番号"),
        sa.Column(
            "type_of_document", sa.String(length=100), nullable=False, comment="開示書類種別"
        ),
        sa.Column(
            "cur_per_type",
            sa.String(length=20),
            nullable=True,
            comment="会計期間種別（1Q/2Q/3Q/FY等）",
        ),
        sa.Column("cur_per_st", sa.Date(), nullable=True, comment="当期開始日"),
        sa.Column("cur_per_en", sa.Date(), nullable=True, comment="当期終了日"),
        sa.Column("cur_fy_st", sa.Date(), nullable=True, comment="当期会計年度開始日"),
        sa.Column("cur_fy_en", sa.Date(), nullable=True, comment="当期会計年度終了日"),
        sa.Column("nxt_fy_st", sa.Date(), nullable=True, comment="翌期会計年度開始日"),
        sa.Column("nxt_fy_en", sa.Date(), nullable=True, comment="翌期会計年度終了日"),
        sa.Column(
            "sales", sa.Numeric(precision=17, scale=2), nullable=True, comment="売上高（百万円）"
        ),
        sa.Column(
            "op", sa.Numeric(precision=17, scale=2), nullable=True, comment="営業利益（百万円）"
        ),
        sa.Column(
            "od_p", sa.Numeric(precision=17, scale=2), nullable=True, comment="経常利益（百万円）"
        ),
        sa.Column(
            "np", sa.Numeric(precision=17, scale=2), nullable=True, comment="当期純利益（百万円）"
        ),
        sa.Column(
            "eps", sa.Numeric(precision=10, scale=2), nullable=True, comment="1株当たり利益（円）"
        ),
        sa.Column(
            "deps", sa.Numeric(precision=10, scale=2), nullable=True, comment="希薄化後EPS（円）"
        ),
        sa.Column(
            "ta", sa.Numeric(precision=17, scale=2), nullable=True, comment="総資産（百万円）"
        ),
        sa.Column(
            "eq", sa.Numeric(precision=17, scale=2), nullable=True, comment="純資産（百万円）"
        ),
        sa.Column(
            "eq_ar", sa.Numeric(precision=5, scale=2), nullable=True, comment="自己資本比率（%）"
        ),
        sa.Column(
            "bps", sa.Numeric(precision=10, scale=2), nullable=True, comment="1株当たり純資産（円）"
        ),
        sa.Column(
            "cfo",
            sa.Numeric(precision=17, scale=2),
            nullable=True,
            comment="営業キャッシュフロー（百万円）",
        ),
        sa.Column(
            "cfi",
            sa.Numeric(precision=17, scale=2),
            nullable=True,
            comment="投資キャッシュフロー（百万円）",
        ),
        sa.Column(
            "cff",
            sa.Numeric(precision=17, scale=2),
            nullable=True,
            comment="財務キャッシュフロー（百万円）",
        ),
        sa.Column(
            "cash_eq",
            sa.Numeric(precision=17, scale=2),
            nullable=True,
            comment="現金及び現金同等物（百万円）",
        ),
        sa.Column("sh_out_fy", sa.Integer(), nullable=True, comment="期末発行済株式数（千株）"),
        sa.Column("tr_sh_fy", sa.Integer(), nullable=True, comment="期末自己株式数（千株）"),
        sa.Column("avg_sh", sa.Integer(), nullable=True, comment="期中平均株式数（千株）"),
        sa.Column(
            "div_1q",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="第1四半期配当金（円）",
        ),
        sa.Column(
            "div_2q",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="第2四半期配当金（円）",
        ),
        sa.Column(
            "div_3q",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="第3四半期配当金（円）",
        ),
        sa.Column(
            "div_fy", sa.Numeric(precision=10, scale=2), nullable=True, comment="期末配当金（円）"
        ),
        sa.Column(
            "div_ann", sa.Numeric(precision=10, scale=2), nullable=True, comment="年間配当金（円）"
        ),
        sa.Column("div_unit", sa.String(length=20), nullable=True, comment="配当単位"),
        sa.Column(
            "div_total_ann",
            sa.Numeric(precision=17, scale=2),
            nullable=True,
            comment="年間配当総額（百万円）",
        ),
        sa.Column(
            "payout_ratio_ann",
            sa.Numeric(precision=5, scale=2),
            nullable=True,
            comment="配当性向（%）",
        ),
        sa.Column(
            "f_div_1q",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="第1四半期配当金予想（円）",
        ),
        sa.Column(
            "f_div_2q",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="第2四半期配当金予想（円）",
        ),
        sa.Column(
            "f_div_3q",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="第3四半期配当金予想（円）",
        ),
        sa.Column(
            "f_div_fy",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="期末配当金予想（円）",
        ),
        sa.Column(
            "f_div_ann",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="年間配当金予想（円）",
        ),
        sa.Column("f_div_unit", sa.String(length=20), nullable=True, comment="配当単位・予想"),
        sa.Column(
            "f_div_total_ann",
            sa.Numeric(precision=17, scale=2),
            nullable=True,
            comment="年間配当総額予想（百万円）",
        ),
        sa.Column(
            "f_payout_ratio_ann",
            sa.Numeric(precision=5, scale=2),
            nullable=True,
            comment="配当性向予想（%）",
        ),
        sa.Column(
            "f_sales_2q",
            sa.Numeric(precision=17, scale=2),
            nullable=True,
            comment="売上高予想・第2四半期末（百万円）",
        ),
        sa.Column(
            "f_op_2q",
            sa.Numeric(precision=17, scale=2),
            nullable=True,
            comment="営業利益予想・第2四半期末（百万円）",
        ),
        sa.Column(
            "f_od_p_2q",
            sa.Numeric(precision=17, scale=2),
            nullable=True,
            comment="経常利益予想・第2四半期末（百万円）",
        ),
        sa.Column(
            "f_np_2q",
            sa.Numeric(precision=17, scale=2),
            nullable=True,
            comment="当期純利益予想・第2四半期末（百万円）",
        ),
        sa.Column(
            "f_eps_2q",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="EPS予想・第2四半期末（円）",
        ),
        sa.Column(
            "f_sales",
            sa.Numeric(precision=17, scale=2),
            nullable=True,
            comment="売上高予想・期末（百万円）",
        ),
        sa.Column(
            "f_op",
            sa.Numeric(precision=17, scale=2),
            nullable=True,
            comment="営業利益予想・期末（百万円）",
        ),
        sa.Column(
            "f_od_p",
            sa.Numeric(precision=17, scale=2),
            nullable=True,
            comment="経常利益予想・期末（百万円）",
        ),
        sa.Column(
            "f_np",
            sa.Numeric(precision=17, scale=2),
            nullable=True,
            comment="当期純利益予想・期末（百万円）",
        ),
        sa.Column(
            "f_eps", sa.Numeric(precision=10, scale=2), nullable=True, comment="EPS予想・期末（円）"
        ),
        sa.Column(
            "nx_f_sales_2q",
            sa.Numeric(precision=17, scale=2),
            nullable=True,
            comment="売上高予想・翌事業年度第2四半期末（百万円）",
        ),
        sa.Column(
            "nx_f_op_2q",
            sa.Numeric(precision=17, scale=2),
            nullable=True,
            comment="営業利益予想・翌事業年度第2四半期末（百万円）",
        ),
        sa.Column(
            "nx_f_od_p_2q",
            sa.Numeric(precision=17, scale=2),
            nullable=True,
            comment="経常利益予想・翌事業年度第2四半期末（百万円）",
        ),
        sa.Column(
            "nx_f_np_2q",
            sa.Numeric(precision=17, scale=2),
            nullable=True,
            comment="当期純利益予想・翌事業年度第2四半期末（百万円）",
        ),
        sa.Column(
            "nx_f_eps_2q",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="EPS予想・翌事業年度第2四半期末（円）",
        ),
        sa.Column(
            "nx_f_sales",
            sa.Numeric(precision=17, scale=2),
            nullable=True,
            comment="売上高予想・翌事業年度期末（百万円）",
        ),
        sa.Column(
            "nx_f_op",
            sa.Numeric(precision=17, scale=2),
            nullable=True,
            comment="営業利益予想・翌事業年度期末（百万円）",
        ),
        sa.Column(
            "nx_f_od_p",
            sa.Numeric(precision=17, scale=2),
            nullable=True,
            comment="経常利益予想・翌事業年度期末（百万円）",
        ),
        sa.Column(
            "nx_f_np",
            sa.Numeric(precision=17, scale=2),
            nullable=True,
            comment="当期純利益予想・翌事業年度期末（百万円）",
        ),
        sa.Column(
            "nx_f_eps",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="EPS予想・翌事業年度期末（円）",
        ),
        sa.Column(
            "nx_f_div_1q",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="第1四半期配当金予想・翌事業年度（円）",
        ),
        sa.Column(
            "nx_f_div_2q",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="第2四半期配当金予想・翌事業年度（円）",
        ),
        sa.Column(
            "nx_f_div_3q",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="第3四半期配当金予想・翌事業年度（円）",
        ),
        sa.Column(
            "nx_f_div_fy",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="期末配当金予想・翌事業年度（円）",
        ),
        sa.Column(
            "nx_f_div_ann",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="年間配当金予想・翌事業年度（円）",
        ),
        sa.Column(
            "nx_f_div_unit", sa.String(length=20), nullable=True, comment="配当単位・翌事業年度予想"
        ),
        sa.Column(
            "nx_f_payout_ratio_ann",
            sa.Numeric(precision=5, scale=2),
            nullable=True,
            comment="配当性向予想・翌事業年度（%）",
        ),
        sa.Column(
            "nc_sales",
            sa.Numeric(precision=17, scale=2),
            nullable=True,
            comment="売上高・非連結（百万円）",
        ),
        sa.Column(
            "nc_op",
            sa.Numeric(precision=17, scale=2),
            nullable=True,
            comment="営業利益・非連結（百万円）",
        ),
        sa.Column(
            "nc_od_p",
            sa.Numeric(precision=17, scale=2),
            nullable=True,
            comment="経常利益・非連結（百万円）",
        ),
        sa.Column(
            "nc_np",
            sa.Numeric(precision=17, scale=2),
            nullable=True,
            comment="当期純利益・非連結（百万円）",
        ),
        sa.Column(
            "nc_eps", sa.Numeric(precision=10, scale=2), nullable=True, comment="EPS・非連結（円）"
        ),
        sa.Column(
            "nc_ta",
            sa.Numeric(precision=17, scale=2),
            nullable=True,
            comment="総資産・非連結（百万円）",
        ),
        sa.Column(
            "nc_eq",
            sa.Numeric(precision=17, scale=2),
            nullable=True,
            comment="純資産・非連結（百万円）",
        ),
        sa.Column(
            "nc_eq_ar",
            sa.Numeric(precision=5, scale=2),
            nullable=True,
            comment="自己資本比率・非連結（%）",
        ),
        sa.Column(
            "nc_bps", sa.Numeric(precision=10, scale=2), nullable=True, comment="BPS・非連結（円）"
        ),
        sa.Column(
            "nc_f_sales_2q",
            sa.Numeric(precision=17, scale=2),
            nullable=True,
            comment="売上高予想・第2四半期末・非連結（百万円）",
        ),
        sa.Column(
            "nc_f_op_2q",
            sa.Numeric(precision=17, scale=2),
            nullable=True,
            comment="営業利益予想・第2四半期末・非連結（百万円）",
        ),
        sa.Column(
            "nc_f_od_p_2q",
            sa.Numeric(precision=17, scale=2),
            nullable=True,
            comment="経常利益予想・第2四半期末・非連結（百万円）",
        ),
        sa.Column(
            "nc_f_np_2q",
            sa.Numeric(precision=17, scale=2),
            nullable=True,
            comment="当期純利益予想・第2四半期末・非連結（百万円）",
        ),
        sa.Column(
            "nc_f_eps_2q",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="EPS予想・第2四半期末・非連結（円）",
        ),
        sa.Column(
            "nc_f_sales",
            sa.Numeric(precision=17, scale=2),
            nullable=True,
            comment="売上高予想・期末・非連結（百万円）",
        ),
        sa.Column(
            "nc_f_op",
            sa.Numeric(precision=17, scale=2),
            nullable=True,
            comment="営業利益予想・期末・非連結（百万円）",
        ),
        sa.Column(
            "nc_f_od_p",
            sa.Numeric(precision=17, scale=2),
            nullable=True,
            comment="経常利益予想・期末・非連結（百万円）",
        ),
        sa.Column(
            "nc_f_np",
            sa.Numeric(precision=17, scale=2),
            nullable=True,
            comment="当期純利益予想・期末・非連結（百万円）",
        ),
        sa.Column(
            "nc_f_eps",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="EPS予想・期末・非連結（円）",
        ),
        sa.Column(
            "nc_nx_f_sales_2q",
            sa.Numeric(precision=17, scale=2),
            nullable=True,
            comment="売上高予想・翌事業年度第2四半期末・非連結（百万円）",
        ),
        sa.Column(
            "nc_nx_f_op_2q",
            sa.Numeric(precision=17, scale=2),
            nullable=True,
            comment="営業利益予想・翌事業年度第2四半期末・非連結（百万円）",
        ),
        sa.Column(
            "nc_nx_f_od_p_2q",
            sa.Numeric(precision=17, scale=2),
            nullable=True,
            comment="経常利益予想・翌事業年度第2四半期末・非連結（百万円）",
        ),
        sa.Column(
            "nc_nx_f_np_2q",
            sa.Numeric(precision=17, scale=2),
            nullable=True,
            comment="当期純利益予想・翌事業年度第2四半期末・非連結（百万円）",
        ),
        sa.Column(
            "nc_nx_f_eps_2q",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="EPS予想・翌事業年度第2四半期末・非連結（円）",
        ),
        sa.Column(
            "nc_nx_f_sales",
            sa.Numeric(precision=17, scale=2),
            nullable=True,
            comment="売上高予想・翌事業年度期末・非連結（百万円）",
        ),
        sa.Column(
            "nc_nx_f_op",
            sa.Numeric(precision=17, scale=2),
            nullable=True,
            comment="営業利益予想・翌事業年度期末・非連結（百万円）",
        ),
        sa.Column(
            "nc_nx_f_od_p",
            sa.Numeric(precision=17, scale=2),
            nullable=True,
            comment="経常利益予想・翌事業年度期末・非連結（百万円）",
        ),
        sa.Column(
            "nc_nx_f_np",
            sa.Numeric(precision=17, scale=2),
            nullable=True,
            comment="当期純利益予想・翌事業年度期末・非連結（百万円）",
        ),
        sa.Column(
            "nc_nx_f_eps",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="EPS予想・翌事業年度期末・非連結（円）",
        ),
        sa.Column(
            "mat_chg_sub", sa.String(length=255), nullable=True, comment="重要な子会社の異動"
        ),
        sa.Column(
            "sig_chg_in_c", sa.String(length=255), nullable=True, comment="連結範囲の重大な変更"
        ),
        sa.Column(
            "chg_by_as_rev",
            sa.String(length=255),
            nullable=True,
            comment="会計基準の改訂による変更",
        ),
        sa.Column(
            "chg_no_as_rev",
            sa.String(length=255),
            nullable=True,
            comment="会計基準の改訂以外による変更",
        ),
        sa.Column(
            "chg_ac_est", sa.String(length=255), nullable=True, comment="会計上の見積りの変更"
        ),
        sa.Column("retro_rst", sa.String(length=255), nullable=True, comment="遡及修正"),
        sa.Column("fetched_at", sa.DateTime(), nullable=False, comment="API取得日時"),
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="主キー（UUID）",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="作成日時",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="更新日時",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "stock_code",
            "disc_date",
            "type_of_document",
            name="uq_financial_statements_code_date_type",
        ),
        comment="財務サマリーデータ（決算短信・業績予想・配当予想）",
    )
    op.create_index(
        "idx_financial_statements_code_date",
        "financial_statements",
        ["stock_code", "disc_date"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "idx_financial_statements_date",
        "financial_statements",
        ["disc_date"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "idx_financial_statements_per_type",
        "financial_statements",
        ["cur_per_type"],
        unique=False,
        postgresql_using="btree",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_financial_statements_per_type",
        table_name="financial_statements",
        postgresql_using="btree",
    )
    op.drop_index(
        "idx_financial_statements_date", table_name="financial_statements", postgresql_using="btree"
    )
    op.drop_index(
        "idx_financial_statements_code_date",
        table_name="financial_statements",
        postgresql_using="btree",
    )
    op.drop_table("financial_statements")
    # ### end Alembic commands ###
