"""unify all numeric columns to precision 17 scale 6

Revision ID: dc9369ff3362
Revises: 02b740f637ec
Create Date: 2026-07-28 22:26:05.445303+09:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dc9369ff3362"
down_revision: str | None = "02b740f637ec"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Increase precision for all NUMERIC columns from (8,4) or (12,4) to (17,6)
    op.alter_column(
        "technical_indicators",
        "deviation_from_ma5",
        existing_type=sa.NUMERIC(precision=8, scale=4),
        type_=sa.Numeric(precision=17, scale=6),
        existing_comment="MA5からの乖離率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "deviation_from_ma25",
        existing_type=sa.NUMERIC(precision=8, scale=4),
        type_=sa.Numeric(precision=17, scale=6),
        existing_comment="MA25からの乖離率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "deviation_from_ma75",
        existing_type=sa.NUMERIC(precision=8, scale=4),
        type_=sa.Numeric(precision=17, scale=6),
        existing_comment="MA75からの乖離率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "deviation_from_ma200",
        existing_type=sa.NUMERIC(precision=8, scale=4),
        type_=sa.Numeric(precision=17, scale=6),
        existing_comment="MA200からの乖離率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "ma_5_25_deviation",
        existing_type=sa.NUMERIC(precision=8, scale=4),
        type_=sa.Numeric(precision=17, scale=6),
        existing_comment="MA5-MA25乖離率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "ma_25_75_deviation",
        existing_type=sa.NUMERIC(precision=8, scale=4),
        type_=sa.Numeric(precision=17, scale=6),
        existing_comment="MA25-MA75乖離率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "ma_75_200_deviation",
        existing_type=sa.NUMERIC(precision=8, scale=4),
        type_=sa.Numeric(precision=17, scale=6),
        existing_comment="MA75-MA200乖離率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "ma_5_slope_5d",
        existing_type=sa.NUMERIC(precision=8, scale=4),
        type_=sa.Numeric(precision=17, scale=6),
        existing_comment="MA5の5日傾き",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "ma_25_slope_5d",
        existing_type=sa.NUMERIC(precision=8, scale=4),
        type_=sa.Numeric(precision=17, scale=6),
        existing_comment="MA25の5日傾き",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "ma_75_slope_10d",
        existing_type=sa.NUMERIC(precision=8, scale=4),
        type_=sa.Numeric(precision=17, scale=6),
        existing_comment="MA75の10日傾き",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "return_1d",
        existing_type=sa.NUMERIC(precision=12, scale=4),
        type_=sa.Numeric(precision=17, scale=6),
        existing_comment="1日騰落率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "return_3d",
        existing_type=sa.NUMERIC(precision=12, scale=4),
        type_=sa.Numeric(precision=17, scale=6),
        existing_comment="3日騰落率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "return_5d",
        existing_type=sa.NUMERIC(precision=12, scale=4),
        type_=sa.Numeric(precision=17, scale=6),
        existing_comment="5日騰落率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "return_10d",
        existing_type=sa.NUMERIC(precision=12, scale=4),
        type_=sa.Numeric(precision=17, scale=6),
        existing_comment="10日騰落率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "return_20d",
        existing_type=sa.NUMERIC(precision=12, scale=4),
        type_=sa.Numeric(precision=17, scale=6),
        existing_comment="20日騰落率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "return_60d",
        existing_type=sa.NUMERIC(precision=12, scale=4),
        type_=sa.Numeric(precision=17, scale=6),
        existing_comment="60日騰落率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "return_120d",
        existing_type=sa.NUMERIC(precision=12, scale=4),
        type_=sa.Numeric(precision=17, scale=6),
        existing_comment="120日騰落率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "log_return_1d",
        existing_type=sa.NUMERIC(precision=8, scale=4),
        type_=sa.Numeric(precision=17, scale=6),
        existing_comment="1日対数収益率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "log_return_5d",
        existing_type=sa.NUMERIC(precision=8, scale=4),
        type_=sa.Numeric(precision=17, scale=6),
        existing_comment="5日対数収益率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "log_return_20d",
        existing_type=sa.NUMERIC(precision=8, scale=4),
        type_=sa.Numeric(precision=17, scale=6),
        existing_comment="20日対数収益率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "roc_12",
        existing_type=sa.NUMERIC(precision=12, scale=4),
        type_=sa.Numeric(precision=17, scale=6),
        existing_comment="12日ROC",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "roc_25",
        existing_type=sa.NUMERIC(precision=12, scale=4),
        type_=sa.Numeric(precision=17, scale=6),
        existing_comment="25日ROC",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "bollinger_position",
        existing_type=sa.NUMERIC(precision=8, scale=4),
        type_=sa.Numeric(precision=17, scale=6),
        existing_comment="バンド内位置（%B）",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "volatility_10d",
        existing_type=sa.NUMERIC(precision=8, scale=4),
        type_=sa.Numeric(precision=17, scale=6),
        existing_comment="10日ボラティリティ",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "volatility_20d",
        existing_type=sa.NUMERIC(precision=8, scale=4),
        type_=sa.Numeric(precision=17, scale=6),
        existing_comment="20日ボラティリティ",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "volatility_60d",
        existing_type=sa.NUMERIC(precision=8, scale=4),
        type_=sa.Numeric(precision=17, scale=6),
        existing_comment="60日ボラティリティ",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "volume_ratio_5",
        existing_type=sa.NUMERIC(precision=12, scale=4),
        type_=sa.Numeric(precision=17, scale=6),
        existing_comment="出来高比率（5日）",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "volume_ratio_20",
        existing_type=sa.NUMERIC(precision=12, scale=4),
        type_=sa.Numeric(precision=17, scale=6),
        existing_comment="出来高比率（20日）",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "volume_change_1d",
        existing_type=sa.NUMERIC(precision=12, scale=4),
        type_=sa.Numeric(precision=17, scale=6),
        existing_comment="1日出来高変化率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "volume_change_5d",
        existing_type=sa.NUMERIC(precision=12, scale=4),
        type_=sa.Numeric(precision=17, scale=6),
        existing_comment="5日出来高変化率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "cmf_20",
        existing_type=sa.NUMERIC(precision=8, scale=4),
        type_=sa.Numeric(precision=17, scale=6),
        existing_comment="20日CMF",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "price_from_high_5d",
        existing_type=sa.NUMERIC(precision=8, scale=4),
        type_=sa.Numeric(precision=17, scale=6),
        existing_comment="5日高値からの乖離率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "price_from_low_5d",
        existing_type=sa.NUMERIC(precision=8, scale=4),
        type_=sa.Numeric(precision=17, scale=6),
        existing_comment="5日安値からの乖離率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "price_from_high_20d",
        existing_type=sa.NUMERIC(precision=8, scale=4),
        type_=sa.Numeric(precision=17, scale=6),
        existing_comment="20日高値からの乖離率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "price_from_low_20d",
        existing_type=sa.NUMERIC(precision=8, scale=4),
        type_=sa.Numeric(precision=17, scale=6),
        existing_comment="20日安値からの乖離率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "price_from_high_52w",
        existing_type=sa.NUMERIC(precision=8, scale=4),
        type_=sa.Numeric(precision=17, scale=6),
        existing_comment="52週高値からの乖離率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "price_from_low_52w",
        existing_type=sa.NUMERIC(precision=8, scale=4),
        type_=sa.Numeric(precision=17, scale=6),
        existing_comment="52週安値からの乖離率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "body_size",
        existing_type=sa.NUMERIC(precision=8, scale=4),
        type_=sa.Numeric(precision=17, scale=6),
        existing_comment="実体サイズ",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "upper_shadow_ratio",
        existing_type=sa.NUMERIC(precision=8, scale=4),
        type_=sa.Numeric(precision=17, scale=6),
        existing_comment="上ヒゲ比率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "lower_shadow_ratio",
        existing_type=sa.NUMERIC(precision=8, scale=4),
        type_=sa.Numeric(precision=17, scale=6),
        existing_comment="下ヒゲ比率",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert precision for all NUMERIC columns from (17,6) to (8,4) or (12,4)
    op.alter_column(
        "technical_indicators",
        "lower_shadow_ratio",
        existing_type=sa.Numeric(precision=17, scale=6),
        type_=sa.NUMERIC(precision=8, scale=4),
        existing_comment="下ヒゲ比率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "upper_shadow_ratio",
        existing_type=sa.Numeric(precision=17, scale=6),
        type_=sa.NUMERIC(precision=8, scale=4),
        existing_comment="上ヒゲ比率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "body_size",
        existing_type=sa.Numeric(precision=17, scale=6),
        type_=sa.NUMERIC(precision=8, scale=4),
        existing_comment="実体サイズ",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "price_from_low_52w",
        existing_type=sa.Numeric(precision=17, scale=6),
        type_=sa.NUMERIC(precision=8, scale=4),
        existing_comment="52週安値からの乖離率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "price_from_high_52w",
        existing_type=sa.Numeric(precision=17, scale=6),
        type_=sa.NUMERIC(precision=8, scale=4),
        existing_comment="52週高値からの乖離率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "price_from_low_20d",
        existing_type=sa.Numeric(precision=17, scale=6),
        type_=sa.NUMERIC(precision=8, scale=4),
        existing_comment="20日安値からの乖離率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "price_from_high_20d",
        existing_type=sa.Numeric(precision=17, scale=6),
        type_=sa.NUMERIC(precision=8, scale=4),
        existing_comment="20日高値からの乖離率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "price_from_low_5d",
        existing_type=sa.Numeric(precision=17, scale=6),
        type_=sa.NUMERIC(precision=8, scale=4),
        existing_comment="5日安値からの乖離率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "price_from_high_5d",
        existing_type=sa.Numeric(precision=17, scale=6),
        type_=sa.NUMERIC(precision=8, scale=4),
        existing_comment="5日高値からの乖離率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "cmf_20",
        existing_type=sa.Numeric(precision=17, scale=6),
        type_=sa.NUMERIC(precision=8, scale=4),
        existing_comment="20日CMF",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "volume_change_5d",
        existing_type=sa.Numeric(precision=17, scale=6),
        type_=sa.NUMERIC(precision=12, scale=4),
        existing_comment="5日出来高変化率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "volume_change_1d",
        existing_type=sa.Numeric(precision=17, scale=6),
        type_=sa.NUMERIC(precision=12, scale=4),
        existing_comment="1日出来高変化率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "volume_ratio_20",
        existing_type=sa.Numeric(precision=17, scale=6),
        type_=sa.NUMERIC(precision=12, scale=4),
        existing_comment="出来高比率（20日）",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "volume_ratio_5",
        existing_type=sa.Numeric(precision=17, scale=6),
        type_=sa.NUMERIC(precision=12, scale=4),
        existing_comment="出来高比率（5日）",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "volatility_60d",
        existing_type=sa.Numeric(precision=17, scale=6),
        type_=sa.NUMERIC(precision=8, scale=4),
        existing_comment="60日ボラティリティ",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "volatility_20d",
        existing_type=sa.Numeric(precision=17, scale=6),
        type_=sa.NUMERIC(precision=8, scale=4),
        existing_comment="20日ボラティリティ",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "volatility_10d",
        existing_type=sa.Numeric(precision=17, scale=6),
        type_=sa.NUMERIC(precision=8, scale=4),
        existing_comment="10日ボラティリティ",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "bollinger_position",
        existing_type=sa.Numeric(precision=17, scale=6),
        type_=sa.NUMERIC(precision=8, scale=4),
        existing_comment="バンド内位置（%B）",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "roc_25",
        existing_type=sa.Numeric(precision=17, scale=6),
        type_=sa.NUMERIC(precision=12, scale=4),
        existing_comment="25日ROC",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "roc_12",
        existing_type=sa.Numeric(precision=17, scale=6),
        type_=sa.NUMERIC(precision=12, scale=4),
        existing_comment="12日ROC",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "log_return_20d",
        existing_type=sa.Numeric(precision=17, scale=6),
        type_=sa.NUMERIC(precision=8, scale=4),
        existing_comment="20日対数収益率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "log_return_5d",
        existing_type=sa.Numeric(precision=17, scale=6),
        type_=sa.NUMERIC(precision=8, scale=4),
        existing_comment="5日対数収益率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "log_return_1d",
        existing_type=sa.Numeric(precision=17, scale=6),
        type_=sa.NUMERIC(precision=8, scale=4),
        existing_comment="1日対数収益率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "return_120d",
        existing_type=sa.Numeric(precision=17, scale=6),
        type_=sa.NUMERIC(precision=12, scale=4),
        existing_comment="120日騰落率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "return_60d",
        existing_type=sa.Numeric(precision=17, scale=6),
        type_=sa.NUMERIC(precision=12, scale=4),
        existing_comment="60日騰落率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "return_20d",
        existing_type=sa.Numeric(precision=17, scale=6),
        type_=sa.NUMERIC(precision=12, scale=4),
        existing_comment="20日騰落率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "return_10d",
        existing_type=sa.Numeric(precision=17, scale=6),
        type_=sa.NUMERIC(precision=12, scale=4),
        existing_comment="10日騰落率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "return_5d",
        existing_type=sa.Numeric(precision=17, scale=6),
        type_=sa.NUMERIC(precision=12, scale=4),
        existing_comment="5日騰落率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "return_3d",
        existing_type=sa.Numeric(precision=17, scale=6),
        type_=sa.NUMERIC(precision=12, scale=4),
        existing_comment="3日騰落率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "return_1d",
        existing_type=sa.Numeric(precision=17, scale=6),
        type_=sa.NUMERIC(precision=12, scale=4),
        existing_comment="1日騰落率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "ma_75_slope_10d",
        existing_type=sa.Numeric(precision=17, scale=6),
        type_=sa.NUMERIC(precision=8, scale=4),
        existing_comment="MA75の10日傾き",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "ma_25_slope_5d",
        existing_type=sa.Numeric(precision=17, scale=6),
        type_=sa.NUMERIC(precision=8, scale=4),
        existing_comment="MA25の5日傾き",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "ma_5_slope_5d",
        existing_type=sa.Numeric(precision=17, scale=6),
        type_=sa.NUMERIC(precision=8, scale=4),
        existing_comment="MA5の5日傾き",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "ma_75_200_deviation",
        existing_type=sa.Numeric(precision=17, scale=6),
        type_=sa.NUMERIC(precision=8, scale=4),
        existing_comment="MA75-MA200乖離率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "ma_25_75_deviation",
        existing_type=sa.Numeric(precision=17, scale=6),
        type_=sa.NUMERIC(precision=8, scale=4),
        existing_comment="MA25-MA75乖離率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "ma_5_25_deviation",
        existing_type=sa.Numeric(precision=17, scale=6),
        type_=sa.NUMERIC(precision=8, scale=4),
        existing_comment="MA5-MA25乖離率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "deviation_from_ma200",
        existing_type=sa.Numeric(precision=17, scale=6),
        type_=sa.NUMERIC(precision=8, scale=4),
        existing_comment="MA200からの乖離率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "deviation_from_ma75",
        existing_type=sa.Numeric(precision=17, scale=6),
        type_=sa.NUMERIC(precision=8, scale=4),
        existing_comment="MA75からの乖離率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "deviation_from_ma25",
        existing_type=sa.Numeric(precision=17, scale=6),
        type_=sa.NUMERIC(precision=8, scale=4),
        existing_comment="MA25からの乖離率",
        existing_nullable=True,
    )
    op.alter_column(
        "technical_indicators",
        "deviation_from_ma5",
        existing_type=sa.Numeric(precision=17, scale=6),
        type_=sa.NUMERIC(precision=8, scale=4),
        existing_comment="MA5からの乖離率",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
