"""add stock prices technical indicators and round results tables

Revision ID: db42c44b1ad6
Revises: 3e798dd4bfb9
Create Date: 2026-07-22 17:43:36.115142+09:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "db42c44b1ad6"
down_revision: str | None = "3e798dd4bfb9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_prices_daily",
        sa.Column("stock_code", sa.String(length=10), nullable=False, comment="銘柄コード"),
        sa.Column("date", sa.Date(), nullable=False, comment="日付"),
        sa.Column("open", sa.Numeric(precision=10, scale=2), nullable=True, comment="始値"),
        sa.Column("high", sa.Numeric(precision=10, scale=2), nullable=True, comment="高値"),
        sa.Column("low", sa.Numeric(precision=10, scale=2), nullable=True, comment="安値"),
        sa.Column("close", sa.Numeric(precision=10, scale=2), nullable=True, comment="終値"),
        sa.Column("volume", sa.Integer(), nullable=True, comment="出来高"),
        sa.Column(
            "turnover_value", sa.Numeric(precision=15, scale=2), nullable=True, comment="売買代金"
        ),
        sa.Column(
            "adjusted_open", sa.Numeric(precision=10, scale=2), nullable=True, comment="調整後始値"
        ),
        sa.Column(
            "adjusted_high", sa.Numeric(precision=10, scale=2), nullable=True, comment="調整後高値"
        ),
        sa.Column(
            "adjusted_low", sa.Numeric(precision=10, scale=2), nullable=True, comment="調整後安値"
        ),
        sa.Column(
            "adjusted_close", sa.Numeric(precision=10, scale=2), nullable=True, comment="調整後終値"
        ),
        sa.Column("adjusted_volume", sa.Integer(), nullable=True, comment="調整後出来高"),
        sa.Column(
            "adjustment_factor",
            sa.Numeric(precision=10, scale=6),
            nullable=True,
            comment="調整係数",
        ),
        sa.Column("is_upper_limit", sa.Boolean(), nullable=False, comment="ストップ高フラグ"),
        sa.Column("is_lower_limit", sa.Boolean(), nullable=False, comment="ストップ安フラグ"),
        sa.Column("fetched_at", sa.DateTime(), nullable=False, comment="API取得日時"),
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="主キー（UUID）",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="作成日時",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="更新日時",
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="株価日次データ",
    )
    op.create_index(
        "idx_stock_prices_daily_code_date",
        "stock_prices_daily",
        ["stock_code", "date"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "idx_stock_prices_daily_date",
        "stock_prices_daily",
        ["date"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_table(
        "technical_indicators",
        sa.Column("stock_code", sa.String(length=10), nullable=False, comment="銘柄コード"),
        sa.Column("date", sa.Date(), nullable=False, comment="日付"),
        sa.Column("ma_5", sa.Numeric(precision=10, scale=2), nullable=True, comment="5日移動平均"),
        sa.Column(
            "ma_10", sa.Numeric(precision=10, scale=2), nullable=True, comment="10日移動平均"
        ),
        sa.Column(
            "ma_25", sa.Numeric(precision=10, scale=2), nullable=True, comment="25日移動平均"
        ),
        sa.Column(
            "ma_50", sa.Numeric(precision=10, scale=2), nullable=True, comment="50日移動平均"
        ),
        sa.Column(
            "ma_75", sa.Numeric(precision=10, scale=2), nullable=True, comment="75日移動平均"
        ),
        sa.Column(
            "ma_100", sa.Numeric(precision=10, scale=2), nullable=True, comment="100日移動平均"
        ),
        sa.Column(
            "ma_200", sa.Numeric(precision=10, scale=2), nullable=True, comment="200日移動平均"
        ),
        sa.Column(
            "ema_5", sa.Numeric(precision=10, scale=2), nullable=True, comment="5日指数移動平均"
        ),
        sa.Column(
            "ema_12", sa.Numeric(precision=10, scale=2), nullable=True, comment="12日指数移動平均"
        ),
        sa.Column(
            "ema_26", sa.Numeric(precision=10, scale=2), nullable=True, comment="26日指数移動平均"
        ),
        sa.Column(
            "ema_50", sa.Numeric(precision=10, scale=2), nullable=True, comment="50日指数移動平均"
        ),
        sa.Column(
            "ema_200", sa.Numeric(precision=10, scale=2), nullable=True, comment="200日指数移動平均"
        ),
        sa.Column(
            "wma_20", sa.Numeric(precision=10, scale=2), nullable=True, comment="20日加重移動平均"
        ),
        sa.Column(
            "deviation_from_ma5",
            sa.Numeric(precision=8, scale=4),
            nullable=True,
            comment="MA5からの乖離率",
        ),
        sa.Column(
            "deviation_from_ma25",
            sa.Numeric(precision=8, scale=4),
            nullable=True,
            comment="MA25からの乖離率",
        ),
        sa.Column(
            "deviation_from_ma75",
            sa.Numeric(precision=8, scale=4),
            nullable=True,
            comment="MA75からの乖離率",
        ),
        sa.Column(
            "deviation_from_ma200",
            sa.Numeric(precision=8, scale=4),
            nullable=True,
            comment="MA200からの乖離率",
        ),
        sa.Column(
            "ma_5_25_deviation",
            sa.Numeric(precision=8, scale=4),
            nullable=True,
            comment="MA5-MA25乖離率",
        ),
        sa.Column(
            "ma_25_75_deviation",
            sa.Numeric(precision=8, scale=4),
            nullable=True,
            comment="MA25-MA75乖離率",
        ),
        sa.Column(
            "ma_75_200_deviation",
            sa.Numeric(precision=8, scale=4),
            nullable=True,
            comment="MA75-MA200乖離率",
        ),
        sa.Column(
            "ma_5_slope_5d", sa.Numeric(precision=8, scale=4), nullable=True, comment="MA5の5日傾き"
        ),
        sa.Column(
            "ma_25_slope_5d",
            sa.Numeric(precision=8, scale=4),
            nullable=True,
            comment="MA25の5日傾き",
        ),
        sa.Column(
            "ma_75_slope_10d",
            sa.Numeric(precision=8, scale=4),
            nullable=True,
            comment="MA75の10日傾き",
        ),
        sa.Column(
            "days_since_gc_5_25", sa.Integer(), nullable=True, comment="MA5×MA25 GCからの日数"
        ),
        sa.Column(
            "days_since_dc_5_25", sa.Integer(), nullable=True, comment="MA5×MA25 DCからの日数"
        ),
        sa.Column(
            "days_since_gc_25_75", sa.Integer(), nullable=True, comment="MA25×MA75 GCからの日数"
        ),
        sa.Column(
            "days_since_dc_25_75", sa.Integer(), nullable=True, comment="MA25×MA75 DCからの日数"
        ),
        sa.Column(
            "is_perfect_order_bullish",
            sa.Boolean(),
            nullable=True,
            comment="パーフェクトオーダー（買い）",
        ),
        sa.Column(
            "is_perfect_order_bearish",
            sa.Boolean(),
            nullable=True,
            comment="パーフェクトオーダー（売り）",
        ),
        sa.Column(
            "return_1d", sa.Numeric(precision=8, scale=4), nullable=True, comment="1日騰落率"
        ),
        sa.Column(
            "return_3d", sa.Numeric(precision=8, scale=4), nullable=True, comment="3日騰落率"
        ),
        sa.Column(
            "return_5d", sa.Numeric(precision=8, scale=4), nullable=True, comment="5日騰落率"
        ),
        sa.Column(
            "return_10d", sa.Numeric(precision=8, scale=4), nullable=True, comment="10日騰落率"
        ),
        sa.Column(
            "return_20d", sa.Numeric(precision=8, scale=4), nullable=True, comment="20日騰落率"
        ),
        sa.Column(
            "return_60d", sa.Numeric(precision=8, scale=4), nullable=True, comment="60日騰落率"
        ),
        sa.Column(
            "return_120d", sa.Numeric(precision=8, scale=4), nullable=True, comment="120日騰落率"
        ),
        sa.Column(
            "log_return_1d",
            sa.Numeric(precision=8, scale=4),
            nullable=True,
            comment="1日対数収益率",
        ),
        sa.Column(
            "log_return_5d",
            sa.Numeric(precision=8, scale=4),
            nullable=True,
            comment="5日対数収益率",
        ),
        sa.Column(
            "log_return_20d",
            sa.Numeric(precision=8, scale=4),
            nullable=True,
            comment="20日対数収益率",
        ),
        sa.Column("rsi_9", sa.Numeric(precision=5, scale=2), nullable=True, comment="RSI(9日)"),
        sa.Column("rsi_14", sa.Numeric(precision=5, scale=2), nullable=True, comment="RSI(14日)"),
        sa.Column("rsi_25", sa.Numeric(precision=5, scale=2), nullable=True, comment="RSI(25日)"),
        sa.Column("macd", sa.Numeric(precision=10, scale=4), nullable=True, comment="MACD"),
        sa.Column(
            "macd_signal", sa.Numeric(precision=10, scale=4), nullable=True, comment="MACDシグナル"
        ),
        sa.Column(
            "macd_histogram",
            sa.Numeric(precision=10, scale=4),
            nullable=True,
            comment="MACDヒストグラム",
        ),
        sa.Column("stochastic_k", sa.Numeric(precision=5, scale=2), nullable=True, comment="%K"),
        sa.Column("stochastic_d", sa.Numeric(precision=5, scale=2), nullable=True, comment="%D"),
        sa.Column(
            "stochastic_slow_d", sa.Numeric(precision=5, scale=2), nullable=True, comment="Slow %D"
        ),
        sa.Column("roc_12", sa.Numeric(precision=8, scale=4), nullable=True, comment="12日ROC"),
        sa.Column("roc_25", sa.Numeric(precision=8, scale=4), nullable=True, comment="25日ROC"),
        sa.Column(
            "momentum_10",
            sa.Numeric(precision=10, scale=4),
            nullable=True,
            comment="10日モメンタム",
        ),
        sa.Column(
            "momentum_20",
            sa.Numeric(precision=10, scale=4),
            nullable=True,
            comment="20日モメンタム",
        ),
        sa.Column("cci_14", sa.Numeric(precision=8, scale=2), nullable=True, comment="14日CCI"),
        sa.Column("cci_20", sa.Numeric(precision=8, scale=2), nullable=True, comment="20日CCI"),
        sa.Column(
            "williams_r_14",
            sa.Numeric(precision=5, scale=2),
            nullable=True,
            comment="14日ウィリアムズ%R",
        ),
        sa.Column("mfi_14", sa.Numeric(precision=5, scale=2), nullable=True, comment="14日MFI"),
        sa.Column(
            "ultimate_oscillator",
            sa.Numeric(precision=5, scale=2),
            nullable=True,
            comment="Ultimate Oscillator",
        ),
        sa.Column("adx_14", sa.Numeric(precision=5, scale=2), nullable=True, comment="14日ADX"),
        sa.Column(
            "plus_di_14", sa.Numeric(precision=5, scale=2), nullable=True, comment="+DI(14日)"
        ),
        sa.Column(
            "minus_di_14", sa.Numeric(precision=5, scale=2), nullable=True, comment="-DI(14日)"
        ),
        sa.Column(
            "parabolic_sar",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="パラボリックSAR値",
        ),
        sa.Column(
            "sar_direction", sa.String(length=10), nullable=True, comment="SAR方向（LONG/SHORT）"
        ),
        sa.Column(
            "tenkan_sen", sa.Numeric(precision=10, scale=2), nullable=True, comment="転換線（9日）"
        ),
        sa.Column(
            "kijun_sen", sa.Numeric(precision=10, scale=2), nullable=True, comment="基準線（26日）"
        ),
        sa.Column(
            "senkou_span_a", sa.Numeric(precision=10, scale=2), nullable=True, comment="先行スパンA"
        ),
        sa.Column(
            "senkou_span_b", sa.Numeric(precision=10, scale=2), nullable=True, comment="先行スパンB"
        ),
        sa.Column(
            "chikou_span", sa.Numeric(precision=10, scale=2), nullable=True, comment="遅行スパン"
        ),
        sa.Column(
            "kumo_thickness", sa.Numeric(precision=10, scale=2), nullable=True, comment="雲の厚さ"
        ),
        sa.Column("is_above_kumo", sa.Boolean(), nullable=True, comment="価格が雲の上"),
        sa.Column("is_below_kumo", sa.Boolean(), nullable=True, comment="価格が雲の下"),
        sa.Column(
            "bollinger_upper_2sigma",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="ボリンジャー上限2σ",
        ),
        sa.Column(
            "bollinger_middle",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="ボリンジャー中心線",
        ),
        sa.Column(
            "bollinger_lower_2sigma",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="ボリンジャー下限2σ",
        ),
        sa.Column(
            "bollinger_width",
            sa.Numeric(precision=10, scale=4),
            nullable=True,
            comment="ボリンジャーバンド幅",
        ),
        sa.Column(
            "bollinger_position",
            sa.Numeric(precision=8, scale=4),
            nullable=True,
            comment="バンド内位置（%B）",
        ),
        sa.Column("atr_14", sa.Numeric(precision=10, scale=4), nullable=True, comment="14日ATR"),
        sa.Column("atr_20", sa.Numeric(precision=10, scale=4), nullable=True, comment="20日ATR"),
        sa.Column(
            "volatility_10d",
            sa.Numeric(precision=8, scale=4),
            nullable=True,
            comment="10日ボラティリティ",
        ),
        sa.Column(
            "volatility_20d",
            sa.Numeric(precision=8, scale=4),
            nullable=True,
            comment="20日ボラティリティ",
        ),
        sa.Column(
            "volatility_60d",
            sa.Numeric(precision=8, scale=4),
            nullable=True,
            comment="60日ボラティリティ",
        ),
        sa.Column(
            "keltner_upper",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="ケルトナー上限",
        ),
        sa.Column(
            "keltner_middle",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="ケルトナー中心",
        ),
        sa.Column(
            "keltner_lower",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="ケルトナー下限",
        ),
        sa.Column("volume_ma_5", sa.Integer(), nullable=True, comment="5日平均出来高"),
        sa.Column("volume_ma_10", sa.Integer(), nullable=True, comment="10日平均出来高"),
        sa.Column("volume_ma_20", sa.Integer(), nullable=True, comment="20日平均出来高"),
        sa.Column("volume_ma_60", sa.Integer(), nullable=True, comment="60日平均出来高"),
        sa.Column(
            "volume_ratio_5",
            sa.Numeric(precision=8, scale=4),
            nullable=True,
            comment="出来高比率（5日）",
        ),
        sa.Column(
            "volume_ratio_20",
            sa.Numeric(precision=8, scale=4),
            nullable=True,
            comment="出来高比率（20日）",
        ),
        sa.Column(
            "volume_change_1d",
            sa.Numeric(precision=8, scale=4),
            nullable=True,
            comment="1日出来高変化率",
        ),
        sa.Column(
            "volume_change_5d",
            sa.Numeric(precision=8, scale=4),
            nullable=True,
            comment="5日出来高変化率",
        ),
        sa.Column("obv", sa.Integer(), nullable=True, comment="OBV"),
        sa.Column("obv_ma_20", sa.Integer(), nullable=True, comment="20日OBV移動平均"),
        sa.Column("vwap", sa.Numeric(precision=10, scale=2), nullable=True, comment="VWAP"),
        sa.Column(
            "vwma_20",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="20日出来高加重移動平均",
        ),
        sa.Column("cmf_20", sa.Numeric(precision=8, scale=4), nullable=True, comment="20日CMF"),
        sa.Column("high_5d", sa.Numeric(precision=10, scale=2), nullable=True, comment="5日高値"),
        sa.Column("low_5d", sa.Numeric(precision=10, scale=2), nullable=True, comment="5日安値"),
        sa.Column("high_20d", sa.Numeric(precision=10, scale=2), nullable=True, comment="20日高値"),
        sa.Column("low_20d", sa.Numeric(precision=10, scale=2), nullable=True, comment="20日安値"),
        sa.Column("high_60d", sa.Numeric(precision=10, scale=2), nullable=True, comment="60日高値"),
        sa.Column("low_60d", sa.Numeric(precision=10, scale=2), nullable=True, comment="60日安値"),
        sa.Column("high_52w", sa.Numeric(precision=10, scale=2), nullable=True, comment="52週高値"),
        sa.Column("low_52w", sa.Numeric(precision=10, scale=2), nullable=True, comment="52週安値"),
        sa.Column(
            "price_from_high_5d",
            sa.Numeric(precision=8, scale=4),
            nullable=True,
            comment="5日高値からの乖離率",
        ),
        sa.Column(
            "price_from_low_5d",
            sa.Numeric(precision=8, scale=4),
            nullable=True,
            comment="5日安値からの乖離率",
        ),
        sa.Column(
            "price_from_high_20d",
            sa.Numeric(precision=8, scale=4),
            nullable=True,
            comment="20日高値からの乖離率",
        ),
        sa.Column(
            "price_from_low_20d",
            sa.Numeric(precision=8, scale=4),
            nullable=True,
            comment="20日安値からの乖離率",
        ),
        sa.Column(
            "price_from_high_52w",
            sa.Numeric(precision=8, scale=4),
            nullable=True,
            comment="52週高値からの乖離率",
        ),
        sa.Column(
            "price_from_low_52w",
            sa.Numeric(precision=8, scale=4),
            nullable=True,
            comment="52週安値からの乖離率",
        ),
        sa.Column(
            "price_position_20d",
            sa.Numeric(precision=5, scale=4),
            nullable=True,
            comment="20日価格相対位置",
        ),
        sa.Column(
            "price_position_52w",
            sa.Numeric(precision=5, scale=4),
            nullable=True,
            comment="52週価格相対位置",
        ),
        sa.Column("is_new_high_20d", sa.Boolean(), nullable=True, comment="20日新高値"),
        sa.Column("is_new_low_20d", sa.Boolean(), nullable=True, comment="20日新安値"),
        sa.Column("is_new_high_52w", sa.Boolean(), nullable=True, comment="52週新高値"),
        sa.Column("is_new_low_52w", sa.Boolean(), nullable=True, comment="52週新安値"),
        sa.Column("is_doji", sa.Boolean(), nullable=True, comment="十字線"),
        sa.Column("is_hammer", sa.Boolean(), nullable=True, comment="ハンマー"),
        sa.Column("is_inverted_hammer", sa.Boolean(), nullable=True, comment="逆ハンマー"),
        sa.Column("is_shooting_star", sa.Boolean(), nullable=True, comment="流れ星"),
        sa.Column("is_hanging_man", sa.Boolean(), nullable=True, comment="首吊り線"),
        sa.Column("consecutive_up_days", sa.Integer(), nullable=True, comment="連続陽線日数"),
        sa.Column("consecutive_down_days", sa.Integer(), nullable=True, comment="連続陰線日数"),
        sa.Column(
            "body_size", sa.Numeric(precision=8, scale=4), nullable=True, comment="実体サイズ"
        ),
        sa.Column(
            "upper_shadow_ratio",
            sa.Numeric(precision=8, scale=4),
            nullable=True,
            comment="上ヒゲ比率",
        ),
        sa.Column(
            "lower_shadow_ratio",
            sa.Numeric(precision=8, scale=4),
            nullable=True,
            comment="下ヒゲ比率",
        ),
        sa.Column(
            "awesome_oscillator",
            sa.Numeric(precision=10, scale=4),
            nullable=True,
            comment="Awesome Oscillator",
        ),
        sa.Column("aroon_up", sa.Numeric(precision=5, scale=2), nullable=True, comment="Aroon Up"),
        sa.Column(
            "aroon_down", sa.Numeric(precision=5, scale=2), nullable=True, comment="Aroon Down"
        ),
        sa.Column(
            "aroon_oscillator",
            sa.Numeric(precision=5, scale=2),
            nullable=True,
            comment="Aroon Oscillator",
        ),
        sa.Column("calculated_at", sa.Date(), nullable=False, comment="計算日時"),
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="主キー（UUID）",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="作成日時",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="更新日時",
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="テクニカル指標",
    )
    op.create_index(
        "idx_technical_indicators_code_date",
        "technical_indicators",
        ["stock_code", "date"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "idx_technical_indicators_date",
        "technical_indicators",
        ["date"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_table(
        "round_results",
        sa.Column("round_id", sa.Uuid(), nullable=False, comment="ラウンドID（UUID）"),
        sa.Column("stock_code", sa.String(length=10), nullable=False, comment="銘柄コード"),
        sa.Column(
            "start_price",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="開始時点の株価",
        ),
        sa.Column(
            "end_price", sa.Numeric(precision=10, scale=2), nullable=True, comment="終了時点の株価"
        ),
        sa.Column(
            "highest_price",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="期間中最高値",
        ),
        sa.Column(
            "lowest_price", sa.Numeric(precision=10, scale=2), nullable=True, comment="期間中最安値"
        ),
        sa.Column(
            "actual_return", sa.Numeric(precision=8, scale=4), nullable=True, comment="実際の騰落率"
        ),
        sa.Column(
            "predicted_return",
            sa.Numeric(precision=8, scale=4),
            nullable=True,
            comment="予測騰落率",
        ),
        sa.Column(
            "prediction_error", sa.Numeric(precision=8, scale=4), nullable=True, comment="予測誤差"
        ),
        sa.Column("prediction_hit", sa.Boolean(), nullable=True, comment="予測が当たったか"),
        sa.Column("entry_shares", sa.Integer(), nullable=False, comment="仮想投資株数"),
        sa.Column(
            "profit_loss", sa.Numeric(precision=10, scale=2), nullable=True, comment="損益金額"
        ),
        sa.Column(
            "profit_loss_rate", sa.Numeric(precision=8, scale=4), nullable=True, comment="損益率"
        ),
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="主キー（UUID）",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="作成日時",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="更新日時",
        ),
        sa.ForeignKeyConstraint(
            ["round_id"],
            ["rounds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="ラウンド結果",
    )
    op.create_index(
        "idx_round_results_code",
        "round_results",
        ["stock_code"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "idx_round_results_round",
        "round_results",
        ["round_id"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(op.f("ix_round_results_round_id"), "round_results", ["round_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_round_results_round_id"), table_name="round_results")
    op.drop_index("idx_round_results_round", table_name="round_results", postgresql_using="btree")
    op.drop_index("idx_round_results_code", table_name="round_results", postgresql_using="btree")
    op.drop_table("round_results")
    op.drop_index(
        "idx_technical_indicators_date", table_name="technical_indicators", postgresql_using="btree"
    )
    op.drop_index(
        "idx_technical_indicators_code_date",
        table_name="technical_indicators",
        postgresql_using="btree",
    )
    op.drop_table("technical_indicators")
    op.drop_index(
        "idx_stock_prices_daily_date", table_name="stock_prices_daily", postgresql_using="btree"
    )
    op.drop_index(
        "idx_stock_prices_daily_code_date",
        table_name="stock_prices_daily",
        postgresql_using="btree",
    )
    op.drop_table("stock_prices_daily")
    # ### end Alembic commands ###
